<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>MyDmsVn.Bootstrap5WinFormUI.Demo</RootNamespace>
    <AssemblyName>MyDmsVn.Bootstrap5WinFormUI.Demo</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\MyDmsVn.Bootstrap5WinFormUI\MyDmsVn.Bootstrap5WinFormUI.csproj" />
  </ItemGroup>
</Project>
